### ISSUE TITLE
Add guide on how to create secret with binary payload

### ISSUE THREAD

**Issue by shawnzhu** [ibm-cloud-docs/secrets-manager#1]
When following the guide on [Create a secret](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-vault-cli#vault-cli-create-static-secret), it should mention that only text based payload is supported. 

I've followed the guide by storing a binary based payload like:

```
$ vault write ibmcloud/arbitrary/secrets payload=@hive.jceks name=hive.jceks 
```

which works but it doesn't work when reading this secret.

I would suggest using base64 to encode binary file before saving it to vault. For instance:

```
base64 -w0 hive.jceks | vault write ibmcloud/arbitrary/secrets payload=- name=hive.jceks labels="encode:base64"
```

**Comment by ccbarragan** [comment]
Hi @shawnzhu, thanks for your feedback!

I've created an issue to track this with my team internally. Will report back after I push the updates.

**Comment by ccbarragan** [comment]
@shawnzhu We've updated the [Create a secret](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-vault-cli#vault-cli-create-static-secret) page to include your example 🎉 

Closing now, thanks again for leaving us feedback!

**Comment by shawnzhu** [comment]
Verified and it works! Thank you
