### ISSUE TITLE
Example code has incorrect URL

### ISSUE THREAD

**Issue by mdarden** [ibm-cloud-docs/secrets-manager#10]
The example Step 3 of [this tutorial ](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-expiring-secrets-part-3&interface=ui#tutorial-expiring-secrets-part-3-prepare)contains an incorrect URL.

The error is highlighted below.  The string 'destinations' should be a component of the URL immediately preceding the <destination_id>, so the example line should be:
url: '<event_notifications_endpoint_url>/destinations/<destination_id>/public_key',
<img width="683" alt="image" src="https://user-images.githubusercontent.com/6511257/160180424-f496d0b7-e938-4688-a14c-171d512445e8.png">

See Event Notifications API docs here:
https://cloud.ibm.com/apidocs/event-notifications/event-notifications#update-destination

**Comment by ccbarragan** [comment]
Hi @mdarden, thank you for your feedback! We've updated the Event Notifications URLs. Thanks for helping us improve our docs -- if you find anything else, let us know.

<img width="1701" alt="image" src="https://user-images.githubusercontent.com/28902259/160639968-53b8ff60-7926-4f63-99de-74947a535923.png">
