### ISSUE TITLE
Issue involving service authorization configuration

### ISSUE THREAD

**Issue by mtreible-ibm** [ibm-cloud-docs/secrets-manager#12]
[This issue](https://github.com/ibm-cloud-docs/openshift/issues/114) was opened for the OpenShift docs. However the user was able to fix the bug by reconfiguring the service authorization between IKS and Secrets Manager. Sharing here in case there is any useful information for the [service authorization steps](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-integrations#create-authorization).

**Comment by h-romeus** [comment]
@marissa-treible 
Thank you for opening this issue! There were no applicable updates that are relevant to our docs. Our team has made contact with IKS.
Please don't hesitate to open additional feedback in the future.
- Hadassa Romeus
