### ISSUE TITLE
Issue on Secrets Manager IAM engine configuration commands

### ISSUE THREAD

**Issue by mlvazqu2** [ibm-cloud-docs/secrets-manager#14]
Found an issue on https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-configure-iam-engine&interface=cli#configure-iam-engine-cli in step 4. The first 2 command have the incorrect service name thus the commands fail.

**Comment by h-romeus** [comment]
@mlvazqu2 
Thank you for opening this issue! I've addressed your feedback and reviewed with the development team. The update is now available. Here is the [link](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-configure-iam-engine&interface=cli#configure-iam-engine-cli).
Please don't hesitate to open additional feedback in the future.
- Hadassa Romeus
