### ISSUE TITLE
Need instructions for Secrets Manager and OpenShift

### ISSUE THREAD

**Issue by acursons** [ibm-cloud-docs/secrets-manager#15]
The document:

https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-kubernetes-secrets

Gives a step by step integration for Kubernetes integration. I attempted to follow this for OpenShift but Step 3.2 fails. I moved to using the OpenShift UI with the provided External Secrets Operator but found that it was not obvious that I needed to create an OperatorConfig instance before creating the SectretsStore and Secret.

We need a clear step by step process for this setup on OpenShift.

**Comment by h-romeus** [comment]
@acursons Thank you for opening this issue! This is a larger item that we will need to prioritize within our team. I've opened an issue internally that we will use for tracking and will be closing this issue for the time being. I will post here when there is an update available. Please don't hesitate to open additional feedback in the future as we're always looking for ways to improve our documentation.
 -Hadassa Romeus
