### ISSUE TITLE
One step is inconsistent with the image provided

### ISSUE THREAD

**Issue by mlvazqu2** [ibm-cloud-docs/secrets-manager#16]
On https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-prepare-order-certificates#authorize-domains, the screenshot provided does not match the steps below the image. On the screenshot it has Reader access whereas the steps indicate Manager. 
It would be best to have the following image instead.
![UpdatedScreenShot](https://user-images.githubusercontent.com/29264329/192380313-ac41a621-319b-4aec-98bb-8f41bc33d00c.png)
I've replaced the Reader access role with Manager.

**Comment by h-romeus** [comment]
@mlvazqu2 
Thank you for opening this issue! I've addressed your feedback and reviewed with the development team. The update is now available. Here's the [link](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-prepare-order-certificates#authorize-domains).
Please don't hesitate to open additional feedback in the future.
- Hadassa Romeus
