### ISSUE TITLE
Link to [Restore to the previous version] missing closing )

### ISSUE THREAD

**Issue by JoachimGross** [ibm-cloud-docs/secrets-manager#17]
**At the page** 

https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-what-is-secret

**In Table 2** 

Table 2. Feature comparison between secret types

**In Column 1** 

[Restore to the previous version](/docs/secrets-manager?topic=secrets-manager-version-history&interface=ui#restore-secrets

The link is shown in clear text, because at the end a `)`is missung.

**Comment by h-romeus** [comment]
@JoachimGross  Thank you for opening this issue! I've addressed your feedback and reviewed with the development team. Please don't hesitate to open additional feedback in the future.

-Hadassa
