### ISSUE TITLE
Link for Kubernetes Service integration is broken

### ISSUE THREAD

**Issue by UpsideDownPicture** [ibm-cloud-docs/secrets-manager#18]
On the Integrations page (https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-integrations), there is a section for Available Integrations.

Under the Description for the Kubernetes Service, is:

"Centrally manage Ingress subdomain certificates and other secrets for your Kubernetes clusters. [Learn more about this integration](https://cloud.ibm.com/docs/containers?topic=containers-ingress-types#manage_certs_secrets_mgr)."

That link provided is broken and does not work

**Comment by h-romeus** [comment]
Hi @UpsideDownPicture, thank you for opening this issue! I've addressed your feedback and reviewed with the development team. The update will be available soon. Please don't hesitate to open additional feedback in the future.
-Hadassa
