### ISSUE TITLE
Links on Accessing secrets don't work

### ISSUE THREAD

**Issue by qrilka** [ibm-cloud-docs/secrets-manager#2]
I suppose the links on "Retrieving a secret from the CLI" and "Retrieving a secret with the API" on the page https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-access-secrets should switch tabs on the page to show CLI/API way to access the secrets. They don't work Google Chrome 89. Also I think it would be much better (i.e. easier to discover) to have these instructions to be on the same page and on on separate tabs.

**Comment by ccbarragan** [comment]
Hi @qrilka, thank you for your feedback! Regarding the issue with the links, I've sent your feedback over to our IBM Cloud platform documentation team. Looks like this is a known issue with a fix on the way... will update the ticket after we make more updates.

**Comment by ccbarragan** [comment]
Hello! While we wait for the fix on this issue, we went ahead and removed the links that weren't working properly:

https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-access-secrets

We've also logged your feedback to improve the discoverability of UI/CLI/API instructions from single page.

Thanks again for helping to improve our docs!
