### ISSUE TITLE
Review topic "secrets-manager-tutorial-kubernetes-secrets"

### ISSUE THREAD

**Issue by massimocaprinali** [ibm-cloud-docs/secrets-manager#20]
In the topic https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-kubernetes-secrets there are some errore in CLI commands:

- Step 3 in [tutorial-kubernetes-secrets-prepare-sm](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-kubernetes-secrets#tutorial-kubernetes-secrets-prepare-sm)
`ibmcloud secrets-manager secret-group-create --resources '[{"name":"my-test-secret-group","description":"Read and write to my test app."}]' --output json` syntax is not correct

- [Step 2](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-kubernetes-secrets#tutorial-kubernetes-secrets-create-secret)
`ibmcloud secrets-manager username_password  --resources '[{"name":"example_username_password","description":"Extended description for my secret.","secret_group_id":"'"$SECRET_GROUP_ID"'","username":"user123","password":"cloudy-rainy-coffee-book","labels":["my-test-cluster","tutorial"]}]' --output json`  syntax is not correct

**Comment by h-romeus** [comment]
This issue is duplicated so I will close it. -Hadassa
