### ISSUE TITLE
Review topic secrets-manager-tutorial-kubernetes-secrets

### ISSUE THREAD

**Issue by massimocaprinali** [ibm-cloud-docs/secrets-manager#21]
In the topic https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-kubernetes-secrets there are some errore in CLI commands:

- Step 3 in [tutorial-kubernetes-secrets-prepare-sm](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-kubernetes-secrets#tutorial-kubernetes-secrets-prepare-sm)
`ibmcloud secrets-manager secret-group-create --resources '[{"name":"my-test-secret-group","description":"Read and write to my test app."}]' --output json` syntax is not correct

- [Step 2](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-kubernetes-secrets#tutorial-kubernetes-secrets-create-secret)
`ibmcloud secrets-manager username_password  --resources '[{"name":"example_username_password","description":"Extended description for my secret.","secret_group_id":"'"$SECRET_GROUP_ID"'","username":"user123","password":"cloudy-rainy-coffee-book","labels":["my-test-cluster","tutorial"]}]' --output json`  syntax is not correct

**Comment by idohubara** [comment]
These examples are using the V1 based CLI.
The new CLI should have these:
```
export SECRET_GROUP_ID=`ibmcloud secrets-manager secret-group-create --name my-test-secret-group --description "Read and write to my test app." --output json | jq -r ".id"`; echo $SECRET_GROUP_ID
```

```
export SECRET_ID=`ibmcloud secrets-manager secret-create  --secret-prototype='{"name": "example-username-password", "secret_type": "username_password", "username":"user123","password":"cloudy-rainy-coffee-book","labels":["my-test-cluster","tutorial"]}' --output json | jq -r ".id"`; echo $SECRET_ID
```

**Comment by IdanAdar** [comment]
Fixed long ago.
