### ISSUE TITLE
Cross Account Secrets Manager

### ISSUE THREAD

**Issue by chrisverrett** [ibm-cloud-docs/secrets-manager#23]
Hi
I had a question about cross-acct secrets manager - was pointed to the channel and found this thread, which someone else asked about a couple of days ago.   https://ibm-cloudplatform.slack.com/archives/C010Z1DQ05N/p1689317238406799

would it be possible to make this part of the FAQs please? 

thanks!
Chris

**Comment by smguilia** [comment]
Hi @chrisverrett!
Thank you for opening this issue. I'm closing it as I've opened a new one internally that can be prioritized.
- Shawna
