### ISSUE TITLE
APIKEY not defined

### ISSUE THREAD

**Issue by lluissabarich** [ibm-cloud-docs/secrets-manager#24]
At the time the tutorials wants the user to:

ibmcloud secrets-manager configuration-create --config-type iam_credentials_configuration --iam-credentials-apikey $API_KEY

... the API_KEY is not yet defined

Could you please fix this or comment?

Thanks.

**Comment by lluissabarich** [comment]
Tutorial address is: https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-access-storage-bucket

**Comment by IdanAdar** [comment]
Sorry for the late response, the tutorial now mentions:

> To configure the IAM secrets engine from the {[cloud]} CLI, run the [**`ibmcloud secrets-manager config-update`**](/docs/secrets-manager?topic=secrets-manager-secrets-manager-cli#secrets-manager-cli-configuration-update-command) command. 
>    
> Be sure to first create an IAM Service ID and API Key [with the required access policies](/docs/secrets-manager?topic=secrets-manager-configure-iam-engine&interface=ui#before-configure-iam-engine). Use the generated API key in the command below.
    {: note}

```sh
    ibmcloud secrets-manager configuration-create --config-type iam_credentials_configuration --iam-credentials-apikey $API_KEY
```
