### ISSUE TITLE
Seems like the IBM Secrets manager teraform link in the documentation is invalid...

### ISSUE THREAD

**Issue by XReyRobert-IBM** [ibm-cloud-docs/secrets-manager#25]
https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-terraform-setup

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/secrets_manager_secret

**Comment by IdanAdar** [comment]
Sorry for the late response. Will be fixed in the next docs update.
