### ISSUE TITLE
API_KEY misleading

### ISSUE THREAD

**Issue by lluissabarich** [ibm-cloud-docs/secrets-manager#26]
ibmcloud secrets-manager configuration-create --config-type iam_credentials_configuration --iam-credentials-apikey $API_KEY

$API_KEY should be $IBM_CLOUD_API_KEY

**Comment by IdanAdar** [comment]
Could you point to the page you saw this? I can't find it.

**Comment by lluissabarich** [comment]
https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-access-storage-bucket

**Comment by IdanAdar** [comment]
Fixed for the next docs push.
