### ISSUE TITLE
Doc makes reference to IBM Cloud Functions which is now deprecated

### ISSUE THREAD

**Issue by jamesbeltonIBM** [ibm-cloud-docs/secrets-manager#28]
In the "Automatically backing up secrets" page, the second para states: 

"Create a script that periodically downloads all of your secrets and then imports them into your backup instance.
[Create a destination and subscription in Event Notifications](https://cloud.ibm.com/docs/event-notifications) that points to an IBM Cloud Functions action. Configure the action to listen for lifecycle events such as secret_created and  secret_rotated. Then, when the action receives the event, the action downloads the secret from one instance and adds it to the backup instance."

Cloud Functions has been deprecated since December 2023 and you cannot create new entities:
"IBM Cloud® Functions is deprecated. Existing Functions entities such as actions, triggers, or sequences will continue to run, but as of 28 December 2023, you can’t create new Functions entities. Existing Functions entities are supported until October 2024. Any Functions entities that still exist on that date will be deleted."

This needs to be updated - perhaps the same functionality can be achieved with Code Engine?

**Comment by IdanAdar** [comment]
Yes. Will update, thanks.
