### ISSUE TITLE
Vault CLI reference doesn't mention secret groups when deleting secrets

### ISSUE THREAD

**Issue by qrilka** [ibm-cloud-docs/secrets-manager#3]
The reference gives 2 variants for adding secrets: with or without secret group id. The section "Delete a secret" only talks about deleting secrets without a secret group and when using that for a secret in a secret group I get:
```
URL: DELETE https://d7ee55c3-a9f7-4ffa-a875-026a77e85c0a.us-south.secrets-manager.appdomain.cloud/v1/ibmcloud/arbitrary/secrets/XXXXX
Code: 404. Errors:


WARNING! The following warnings were returned from Vault:

  * could not find a secret with the given secretId:
  XXXXX
```

After I added `groups/${SECRET_GROUP_ID}` to the path the deletion completed successfully.

It looks like the documentation should be updated

**Comment by ccbarragan** [comment]
Hi @qrilka. We've updated the example for deleting secrets as part of a documentation release today.

https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-vault-cli#vault-cli-delete-static-secret

Thank you for helping to improve our docs!
