### ISSUE TITLE
Im getting Error flowing the doc

### ISSUE THREAD

**Issue by chechuironman** [ibm-cloud-docs/secrets-manager#4]
status:
  lastSync: '2021-09-14T19:48:16.695Z'
  observedGeneration: 1
  status: 'ERROR, no matching operation was found'

is this working on Openshift 4.7?

**Comment by csantanapr** [comment]
@chechuironman you're referring to this tutorial on the docs? https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-kubernetes-secrets

**Comment by chechuironman** [comment]
yes, thought it was linked the issue to the tutorial sorry

**Comment by ccbarragan** [comment]
@chechuironman Thanks for opening an issue!

@karnatip Can you comment on this?

**Comment by ccbarragan** [comment]
If no further discussions, closing this. Feel free to reopen if there's still an issue.

For questions about Kubernetes External Secrets, please reach out in https://github.com/external-secrets/kubernetes-external-secrets. Thanks!
