### ISSUE TITLE
CLI command to create instance does not work as documented

### ISSUE THREAD

**Issue by CayoM** [ibm-cloud-docs/secrets-manager#5]
Using the described command from the docs
```
ibmcloud resource service-instance-create <instance_name> secrets-manager lite
```
leads to a syntax error. When appending a location to the command i could successfully create an instance:
```
ibmcloud resource service-instance-create <instance_name> secrets-manager lite <location>
```

**Comment by ccbarragan** [comment]
Hi @CayoM, thanks opening an issue. We've fixed this in our latest documentation release. 

https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-create-instance&interface=cli

If you come across anything else, let us know -- thank you for helping to improve our docs!
