### ISSUE TITLE
deprecated kubernetes-external-secrets replaced by operator

### ISSUE THREAD

**Issue by rjminsha** [ibm-cloud-docs/secrets-manager#9]
https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-kubernetes-secrets documentation points user to install from https://github.com/external-secrets/kubernetes-external-secrets which is deprecated.  

```
This project has been [deprecated](https://github.com/external-secrets/kubernetes-external-secrets/issues/864). Please take a look at ESO (External Secrets Operator) instead https://github.com/external-secrets/external-secrets
```

Docs perhaps should be updated with install directions using operator

**Comment by ccbarragan** [comment]
Hi @rjminsha, sorry for the late reply on this!

We're working on updating our docs to update the install instructions using External Secrets Operator -- will post here after the changes are complete. Thank you!

**Comment by ccbarragan** [comment]
We've updated our tutorial to support the latest Externral Secrets Operator: https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-kubernetes-secrets
